/**
 * Tamil Nadu government knowledge base - starter reference data.
 *
 * Loaded through the same tables the configuration UI writes to, so every entry
 * can be edited, deactivated or deleted from the screen without touching code.
 *
 * IMPORTANT, and stated plainly because it matters:
 *
 *   These records carry the NAME, year and subject area of real Acts and
 *   departments. They do NOT carry verified statutory text. Section text,
 *   where present, is a plain-language description of the subject matter, not
 *   a quotation of the provision.
 *
 *   Every record is therefore seeded with verification_status = 'UNVERIFIED'.
 *   An administrator must confirm each entry against the Gazette or the
 *   official publication and record the source before it is relied upon. The
 *   analyser surfaces this status so an officer always knows what they are
 *   looking at.
 *
 * This is a structured starting point, not a claim of completeness or currency.
 */

export interface ActSeed {
  short_name: string;
  full_title: string;
  act_type: 'ACT' | 'RULE' | 'GO' | 'CIRCULAR' | 'POLICY';
  year: number | null;
  jurisdiction: 'CENTRAL' | 'STATE';
  /** Subject area, used for matching. Not a legal summary. */
  applies_when: string;
  keywords: string;
  departments: string[];
  required_documents?: string;
  recommended_action?: string;
  priority?: string;
}

export interface DeptSeed {
  code: string;
  name: string;
  responsibilities: string;
  keywords: string;
}

// ============================================================ DEPARTMENTS
// Tamil Nadu government departments and administrative areas.
export const TN_DEPARTMENTS: DeptSeed[] = [
  { code: 'AGRI', name: 'Agriculture and Farmers Welfare',
    responsibilities: 'Agricultural schemes, crop support, farmer welfare, irrigation support, seeds and fertiliser supply, crop insurance and agricultural extension.',
    keywords: 'agriculture, farmer, crop, seed, fertiliser, irrigation, harvest, cultivation, paddy, farming, agricultural loan, crop insurance' },
  { code: 'ADW', name: 'Adi Dravidar and Tribal Welfare',
    responsibilities: 'Welfare of Scheduled Castes and Scheduled Tribes, community certificates, hostel facilities, scholarships and atrocity-related welfare support.',
    keywords: 'adi dravidar, scheduled caste, scheduled tribe, tribal, sc st, community certificate, caste certificate, atrocity, hostel, scholarship' },
  { code: 'AHDF', name: 'Animal Husbandry, Dairying, Fisheries and Fishermen Welfare',
    responsibilities: 'Livestock, veterinary services, dairy development, fisheries, fishermen welfare and marine resources.',
    keywords: 'cattle, livestock, veterinary, dairy, milk, fisheries, fishermen, boat, fishing, marine, poultry, animal' },
  { code: 'BCMBC', name: 'Backward Classes, Most Backward Classes and Minorities Welfare',
    responsibilities: 'Welfare of backward classes, most backward classes, denotified communities and minorities; community certificates and scholarships.',
    keywords: 'backward class, most backward, mbc, bc, minority, denotified, community certificate, scholarship, welfare' },
  { code: 'COOP', name: 'Co-operation, Food and Consumer Protection',
    responsibilities: 'Co-operative societies, public distribution system, ration cards, fair price shops, consumer protection and food supply.',
    keywords: 'cooperative, co-operative society, ration card, public distribution, fair price shop, pds, consumer, food supply, rice, provisions' },
  { code: 'CTR', name: 'Commercial Taxes and Registration',
    responsibilities: 'Commercial taxes, GST administration, registration of documents, sub registrar offices, stamp duty and encumbrance certificates.',
    keywords: 'registration, sale deed, sub registrar, encumbrance certificate, stamp duty, gst, commercial tax, document registration, guideline value, deed' },
  { code: 'ENV', name: 'Environment, Climate Change and Forests',
    responsibilities: 'Environmental protection, pollution control, forest conservation, wildlife protection, climate change and biodiversity.',
    keywords: 'pollution, environment, forest, wildlife, tree, air pollution, water pollution, effluent, climate, biodiversity, sewage, noise' },
  { code: 'FIN', name: 'Finance',
    responsibilities: 'State finances, budget, treasury, pension payments, small savings and financial administration.',
    keywords: 'finance, budget, treasury, pension payment, salary, arrears, financial, funds, allowance' },
  { code: 'HHTK', name: 'Handlooms, Handicrafts, Textiles and Khadi',
    responsibilities: 'Handloom weavers, handicraft artisans, textile industry and khadi and village industries.',
    keywords: 'handloom, weaver, handicraft, textile, khadi, artisan, loom, silk, cotton' },
  { code: 'HEALTH', name: 'Health and Family Welfare',
    responsibilities: 'Public health, government hospitals, primary health centres, medical treatment, family welfare, drugs control and clinical establishments.',
    keywords: 'hospital, health, medical, doctor, treatment, phc, primary health centre, medicine, ambulance, clinic, patient, surgery, illness' },
  { code: 'HIGHEDU', name: 'Higher Education',
    responsibilities: 'Universities, colleges, technical education, higher education admissions, scholarships and regulation of private colleges.',
    keywords: 'college, university, higher education, degree, admission, engineering college, polytechnic, ragging, student, professor' },
  { code: 'HOME', name: 'Home, Prohibition and Excise',
    responsibilities: 'Police administration, law and order, prisons, prohibition and excise, fire services and public safety.',
    keywords: 'police, complaint, fir, law and order, prison, prohibition, liquor, tasmac, excise, fire service, crime, safety, station' },
  { code: 'HOUSING', name: 'Housing and Urban Development',
    responsibilities: 'Housing schemes, slum clearance, urban development, town planning, building approvals and real estate regulation.',
    keywords: 'housing, house, slum, urban development, town planning, building approval, cmda, rera, apartment, tenement, plan approval' },
  { code: 'IND', name: 'Industries, Investment Promotion and Commerce',
    responsibilities: 'Industrial development, investment promotion, industrial estates, mines and minerals.',
    keywords: 'industry, factory, industrial, investment, sipcot, mines, mineral, quarry, manufacturing' },
  { code: 'ITDS', name: 'Information Technology and Digital Services',
    responsibilities: 'e-Governance, digital services, IT infrastructure, cyber matters and the government data centre.',
    keywords: 'online, website, portal, e-governance, digital, cyber, internet, application status, it' },
  { code: 'LABOUR', name: 'Labour Welfare and Skill Development',
    responsibilities: 'Labour welfare, wages, employment, industrial disputes, workplace safety, skill development, ESI and provident fund matters.',
    keywords: 'labour, worker, wages, salary, employment, industrial dispute, factory safety, esi, provident fund, pf, skill, unemployment, bonded labour, child labour' },
  { code: 'LAW', name: 'Law',
    responsibilities: 'Legal affairs, legal aid, courts administration support and legal opinion.',
    keywords: 'legal, law, court, advocate, legal aid, lok adalat, case, litigation, judgement' },
  { code: 'MSME', name: 'Micro, Small and Medium Enterprises',
    responsibilities: 'Micro, small and medium enterprise promotion, subsidies and entrepreneurship support.',
    keywords: 'msme, small enterprise, entrepreneur, subsidy, business loan, startup, small business' },
  { code: 'MAWS', name: 'Municipal Administration and Water Supply',
    responsibilities: 'Municipal corporations and municipalities, drinking water supply, sewerage, solid waste, streetlights and urban sanitation.',
    keywords: 'municipality, corporation, drinking water, water supply, sewerage, drainage, garbage, street light, sanitation, road, underground drainage, tap' },
  { code: 'PUBLIC', name: 'Public Department',
    responsibilities: 'General administration, public grievances, coordination and matters not falling within a single department.',
    keywords: 'grievance, petition, general, public, coordination, complaint, redressal, request' },
  { code: 'PWD', name: 'Public Works',
    responsibilities: 'Government buildings, irrigation works, water resources structures and public construction.',
    keywords: 'public works, building, construction, canal, dam, tank, irrigation work, bridge, government building' },
  { code: 'REVENUE', name: 'Revenue and Disaster Management',
    responsibilities: 'Land records, patta and chitta, survey and subdivision, mutation, land encroachment, revenue certificates, village administration and disaster relief.',
    keywords: 'land, patta, chitta, survey number, revenue record, mutation, encroachment, village administrative officer, tahsildar, natham, poramboke, land dispute, certificate, disaster, relief, flood' },
  { code: 'RDPR', name: 'Rural Development and Panchayat Raj',
    responsibilities: 'Village panchayats, rural roads, rural employment schemes, rural housing and panchayat administration.',
    keywords: 'panchayat, village, rural, gram sabha, mgnrega, rural road, rural employment, president, panchayat union, block development' },
  { code: 'SCHEDU', name: 'School Education',
    responsibilities: 'Government and private schools, school admissions, teachers, school fees regulation and mid-day meals.',
    keywords: 'school, student, teacher, admission, school fee, education, mid day meal, headmaster, class, rte, textbook' },
  { code: 'SWWE', name: 'Social Welfare and Women Empowerment',
    responsibilities: 'Women welfare, child welfare, nutrition and ICDS, old age and widow pensions, destitute assistance, senior citizen welfare and social security schemes.',
    keywords: 'pension, old age pension, widow pension, welfare, senior citizen, elderly, destitute, women, child, anganwadi, icds, nutrition, maintenance, social security, marriage assistance, aged, livelihood' },
  { code: 'TAMILDEV', name: 'Tamil Development and Information',
    responsibilities: 'Tamil language development, government information, publicity and archives.',
    keywords: 'tamil, language, information, publicity, archives, cultural' },
  { code: 'TOURISM', name: 'Tourism, Culture and Religious Endowments',
    responsibilities: 'Tourism development, culture, temples and religious and charitable endowments.',
    keywords: 'temple, tourism, culture, endowment, hr ce, religious, festival, heritage, archaeology' },
  { code: 'TRANSPORT', name: 'Transport',
    responsibilities: 'Motor vehicles, driving licences, vehicle registration, public transport and road safety.',
    keywords: 'bus, vehicle, driving licence, rto, transport, motor vehicle, registration certificate, permit, road safety, accident, fitness certificate' },
  { code: 'WATERRES', name: 'Water Resources',
    responsibilities: 'Irrigation, rivers, tanks, canals, groundwater and water resource management.',
    keywords: 'irrigation, canal, river, tank, water resource, groundwater, dam, waterbody, kulam, eri' },
  { code: 'WDAP', name: 'Welfare of Differently Abled Persons',
    responsibilities: 'Welfare of persons with disability, disability certificates, assistive devices, pensions and accessibility.',
    keywords: 'disability, differently abled, handicapped, disabled, wheelchair, disability certificate, accessibility, blind, deaf' },
  { code: 'ENERGY', name: 'Energy',
    responsibilities: 'Electricity supply, power connections, tariff matters and renewable energy.',
    keywords: 'electricity, power, current, eb, tangedco, meter, transformer, power cut, connection, tariff, solar' },
  { code: 'HIGHWAYS', name: 'Highways and Minor Ports',
    responsibilities: 'State highways, road construction and maintenance, bridges and minor ports.',
    keywords: 'highway, road, bridge, road repair, pothole, port, national highway, bypass' },
  { code: 'PLANNING', name: 'Planning, Development and Special Initiatives',
    responsibilities: 'State planning, development programmes and special initiatives.',
    keywords: 'planning, development programme, scheme, special initiative, statistics' },
  { code: 'PAR', name: 'Personnel and Administrative Reforms',
    responsibilities: 'Government service matters, administrative reforms, public grievance machinery and right to information administration.',
    keywords: 'government service, transfer, promotion, administrative reform, rti, right to information, service matter, government servant' },
  { code: 'HRM', name: 'Human Resources Management',
    responsibilities: 'Recruitment, service conditions and human resource administration in government.',
    keywords: 'recruitment, appointment, service condition, tnpsc, employment, government job, seniority' },
  { code: 'ASSEMBLY', name: 'Legislative Assembly',
    responsibilities: 'Legislative Assembly administration and legislative business.',
    keywords: 'assembly, legislature, mla, legislative' },
  { code: 'ELECTION', name: 'Public Functions including Election and Rehabilitation',
    responsibilities: 'Elections, electoral rolls, voter matters and rehabilitation programmes.',
    keywords: 'election, voter, voter id, electoral roll, polling, epic, rehabilitation' },
  { code: 'SPI', name: 'Special Programme Implementation',
    responsibilities: 'Implementation and monitoring of special government programmes.',
    keywords: 'special programme, implementation, monitoring, scheme implementation' },
  { code: 'YOUTH', name: 'Youth Welfare and Sports Development',
    responsibilities: 'Youth welfare, sports development, stadiums and sports schemes.',
    keywords: 'youth, sports, stadium, athlete, games, playground, sport' },
  { code: 'NATRES', name: 'Natural Resources',
    responsibilities: 'Natural resource administration and conservation.',
    keywords: 'natural resource, mineral, sand, conservation, resource' },
  { code: 'HRCE', name: 'Religious and Charitable Endowments',
    responsibilities: 'Administration of Hindu religious institutions, temple lands and charitable endowments.',
    keywords: 'temple, hr ce, endowment, religious institution, temple land, trustee, charitable' },
  { code: 'SOCDEF', name: 'Social Defence',
    responsibilities: 'Juvenile justice, children in need of care, beggar homes and social defence institutions.',
    keywords: 'juvenile, child care, children home, beggar, social defence, child protection, orphan' },
  { code: 'ICDS', name: 'Nutrition / ICDS',
    responsibilities: 'Integrated child development services, anganwadi centres, supplementary nutrition and maternal nutrition.',
    keywords: 'anganwadi, nutrition, icds, child nutrition, noon meal, maternal, supplementary nutrition' },
  { code: 'KVIC', name: 'Rural Industries / Khadi and Village Industries',
    responsibilities: 'Rural industries, khadi and village industries and rural employment generation.',
    keywords: 'khadi, village industry, rural industry, cottage industry, handmade' },
  { code: 'COOPAUDIT', name: 'Co-operative Audit',
    responsibilities: 'Audit of co-operative societies.',
    keywords: 'cooperative audit, society audit, audit' },
  { code: 'TREASURY', name: 'Treasuries and Accounts',
    responsibilities: 'Treasury operations, government accounts and payments.',
    keywords: 'treasury, accounts, payment, bill, government account' },
  { code: 'LFA', name: 'Local Fund Audit',
    responsibilities: 'Audit of local bodies and local funds.',
    keywords: 'local fund, audit, local body audit' },
  { code: 'PENSION', name: 'Pension',
    responsibilities: 'Government servant pension sanction, pension revision and pensioner grievances.',
    keywords: 'pension, pensioner, retirement, gratuity, commutation, family pension, pension arrears' },
  { code: 'SMALLSAV', name: 'Small Savings',
    responsibilities: 'Small savings schemes and deposit mobilisation.',
    keywords: 'small savings, deposit, savings scheme, agent' },
  { code: 'EGOV', name: 'Government Data Centre / e-Governance',
    responsibilities: 'Government data centre, e-governance platforms and digital service delivery.',
    keywords: 'data centre, e-governance, online service, digital service, server, portal' },
];

// ================================================================== ACTS
const C = 'CENTRAL' as const;
const S = 'STATE' as const;
const A = 'ACT' as const;
const F = 'POLICY' as const;   // used for "current framework" entries

export const TN_ACTS: ActSeed[] = [
  // ---------------- Central Acts ----------------
  { short_name: 'Maintenance and Welfare of Parents and Senior Citizens Act, 2007',
    full_title: 'The Maintenance and Welfare of Parents and Senior Citizens Act, 2007',
    act_type: A, year: 2007, jurisdiction: C,
    applies_when: 'A parent or senior citizen is unable to maintain themselves, or states that property was transferred to children or relatives who then failed to provide maintenance or basic amenities.',
    keywords: 'senior citizen, elderly, parent, maintenance, old age, aged, welfare of parents, property transferred, unable to maintain, son, daughter, children, destitute, grandmother, grandfather, abandoned',
    departments: ['SWWE', 'REVENUE'],
    required_documents: 'Proof of age, proof of relationship, property document if a transfer is alleged, identity proof.',
    recommended_action: 'Examine whether the petitioner may apply to the Maintenance Tribunal. Officer to verify eligibility and advise accordingly.',
    priority: 'HIGH' },

  { short_name: 'Protection of Women from Domestic Violence Act, 2005',
    full_title: 'The Protection of Women from Domestic Violence Act, 2005',
    act_type: A, year: 2005, jurisdiction: C,
    applies_when: 'A woman states that she has faced violence, harassment, cruelty or deprivation within a domestic relationship.',
    keywords: 'domestic violence, woman, wife, harassment, cruelty, husband, in-laws, dowry harassment, protection officer, abuse, beaten',
    departments: ['SWWE', 'HOME'],
    required_documents: 'Identity proof, address proof, any medical record, any earlier complaint.',
    recommended_action: 'Refer to the Protection Officer and the District Social Welfare Officer. Officer to verify.',
    priority: 'URGENT' },

  { short_name: 'Right of Children to Free and Compulsory Education Act, 2009',
    full_title: 'The Right of Children to Free and Compulsory Education Act, 2009',
    act_type: A, year: 2009, jurisdiction: C,
    applies_when: 'A petition concerns denial of school admission, school fees, or a child being kept out of elementary education.',
    keywords: 'school admission, right to education, rte, child education, school fee, denied admission, elementary education, dropout, student',
    departments: ['SCHEDU'],
    required_documents: 'Birth certificate, address proof, previous school record if any.',
    priority: 'HIGH' },

  { short_name: 'Juvenile Justice (Care and Protection of Children) Act, 2015',
    full_title: 'The Juvenile Justice (Care and Protection of Children) Act, 2015',
    act_type: A, year: 2015, jurisdiction: C,
    applies_when: 'A petition concerns a child in need of care and protection, or a child in conflict with law.',
    keywords: 'child, juvenile, minor, child protection, children home, orphan, abandoned child, child welfare committee, care and protection',
    departments: ['SOCDEF', 'SWWE'],
    priority: 'URGENT' },

  { short_name: 'Rights of Persons with Disabilities Act, 2016',
    full_title: 'The Rights of Persons with Disabilities Act, 2016',
    act_type: A, year: 2016, jurisdiction: C,
    applies_when: 'A petition concerns disability certification, benefits, reservation, accessibility or discrimination against a person with disability.',
    keywords: 'disability, differently abled, disabled, handicapped, disability certificate, wheelchair, accessibility, blind, deaf, disability pension, reservation',
    departments: ['WDAP', 'SWWE'],
    required_documents: 'Disability certificate, medical records, identity proof.',
    priority: 'HIGH' },

  { short_name: 'SC/ST (Prevention of Atrocities) Act, 1989',
    full_title: 'The Scheduled Castes and the Scheduled Tribes (Prevention of Atrocities) Act, 1989',
    act_type: A, year: 1989, jurisdiction: C,
    applies_when: 'A petition alleges an offence or atrocity against a member of a Scheduled Caste or Scheduled Tribe.',
    keywords: 'atrocity, scheduled caste, scheduled tribe, sc st, caste discrimination, untouchability, caste abuse, dalit',
    departments: ['ADW', 'HOME'],
    required_documents: 'Community certificate, any police complaint, witness particulars.',
    priority: 'URGENT' },

  { short_name: 'Right to Information Act, 2005',
    full_title: 'The Right to Information Act, 2005',
    act_type: A, year: 2005, jurisdiction: C,
    applies_when: 'A petition concerns an information request to a public authority, delay in reply, or refusal of information.',
    keywords: 'right to information, rti, information request, public information officer, pio, appeal, information denied, transparency',
    departments: ['PAR'],
    required_documents: 'Copy of the RTI application, any reply received, proof of fee paid.' },

  { short_name: 'Legal Services Authorities Act, 1987',
    full_title: 'The Legal Services Authorities Act, 1987',
    act_type: A, year: 1987, jurisdiction: C,
    applies_when: 'A petitioner may be eligible for free legal aid, or the matter is suitable for lok adalat.',
    keywords: 'legal aid, free legal, lok adalat, legal services, advocate, legal counselling, eligible person',
    departments: ['LAW'] },

  { short_name: 'Consumer Protection Act, 2019',
    full_title: 'The Consumer Protection Act, 2019',
    act_type: A, year: 2019, jurisdiction: C,
    applies_when: 'A petition concerns a defective product, deficiency in service, unfair trade practice or overcharging by a trader or service provider.',
    keywords: 'consumer, defective, deficiency in service, refund, warranty, unfair trade, shop, trader, overcharge, product, service complaint',
    departments: ['COOP'] },

  { short_name: 'Real Estate (Regulation and Development) Act, 2016',
    full_title: 'The Real Estate (Regulation and Development) Act, 2016',
    act_type: A, year: 2016, jurisdiction: C,
    applies_when: 'A petition concerns a builder, promoter, delayed possession of a flat or plot, or a registered real estate project.',
    keywords: 'builder, promoter, flat, apartment, possession delay, rera, real estate, booking amount, project, construction delay',
    departments: ['HOUSING'] },

  { short_name: 'Information Technology Act, 2000',
    full_title: 'The Information Technology Act, 2000',
    act_type: A, year: 2000, jurisdiction: C,
    applies_when: 'A petition concerns cyber fraud, online abuse, data misuse or an electronic record.',
    keywords: 'cyber, online fraud, hacking, digital, electronic record, online abuse, social media, otp fraud, phishing',
    departments: ['ITDS', 'HOME'] },

  { short_name: 'Motor Vehicles Act, 1988',
    full_title: 'The Motor Vehicles Act, 1988',
    act_type: A, year: 1988, jurisdiction: C,
    applies_when: 'A petition concerns a driving licence, vehicle registration, permit, road accident compensation or transport regulation.',
    keywords: 'driving licence, vehicle, registration certificate, rto, permit, accident, motor vehicle, insurance claim, fitness, transport',
    departments: ['TRANSPORT'] },

  { short_name: 'Environment (Protection) Act, 1986',
    full_title: 'The Environment (Protection) Act, 1986',
    act_type: A, year: 1986, jurisdiction: C,
    applies_when: 'A petition concerns environmental damage, hazardous discharge or a polluting activity.',
    keywords: 'environment, pollution, hazardous, contamination, environmental damage, effluent, waste dumping',
    departments: ['ENV'] },

  { short_name: 'Water (Prevention and Control of Pollution) Act, 1974',
    full_title: 'The Water (Prevention and Control of Pollution) Act, 1974',
    act_type: A, year: 1974, jurisdiction: C,
    applies_when: 'A petition concerns contamination of water, discharge of effluent into a waterbody, or water pollution by an industry.',
    keywords: 'water pollution, effluent discharge, sewage discharge, contaminated water, river pollution, polluted water, industrial discharge, borewell contamination, நீர் மாசு, கழிவுநீர் கலப்பு, தொழிற்சாலை கழிவு',
    departments: ['ENV'] },

  { short_name: 'Air (Prevention and Control of Pollution) Act, 1981',
    full_title: 'The Air (Prevention and Control of Pollution) Act, 1981',
    act_type: A, year: 1981, jurisdiction: C,
    applies_when: 'A petition concerns air pollution, smoke, dust or emissions from an industry or activity.',
    keywords: 'air pollution, smoke, dust, emission, fumes, burning, chimney, air quality',
    departments: ['ENV'] },

  { short_name: 'Wild Life (Protection) Act, 1972',
    full_title: 'The Wild Life (Protection) Act, 1972',
    act_type: A, year: 1972, jurisdiction: C,
    applies_when: 'A petition concerns wildlife, animal poaching, human-wildlife conflict or a protected area.',
    keywords: 'wildlife, wild animal, elephant, poaching, forest animal, sanctuary, crop damage by animals, snake, monkey',
    departments: ['ENV'] },

  { short_name: 'Forest (Conservation) Act, 1980',
    full_title: 'The Forest (Conservation) Act, 1980',
    act_type: A, year: 1980, jurisdiction: C,
    applies_when: 'A petition concerns forest land, diversion of forest land or forest rights.',
    keywords: 'forest land, forest, tree felling, forest right, reserve forest, forest encroachment',
    departments: ['ENV'] },

  { short_name: 'Biological Diversity Act, 2002',
    full_title: 'The Biological Diversity Act, 2002',
    act_type: A, year: 2002, jurisdiction: C,
    applies_when: 'A petition concerns biological resources, biodiversity conservation or access to genetic resources.',
    keywords: 'biodiversity, biological resource, conservation, genetic resource, species',
    departments: ['ENV'] },

  { short_name: 'RFCTLARR Act, 2013',
    full_title: 'The Right to Fair Compensation and Transparency in Land Acquisition, Rehabilitation and Resettlement Act, 2013',
    act_type: A, year: 2013, jurisdiction: C,
    applies_when: 'A petition concerns acquisition of land by government, compensation for acquired land, or rehabilitation and resettlement.',
    keywords: 'land acquisition, compensation, acquired land, rehabilitation, resettlement, award, government acquisition, highway acquisition',
    departments: ['REVENUE'],
    required_documents: 'Patta, acquisition notification, award copy if issued, identity proof.',
    priority: 'HIGH' },

  { short_name: 'Registration Act, 1908',
    full_title: 'The Registration Act, 1908',
    act_type: A, year: 1908, jurisdiction: C,
    applies_when: 'A petition concerns registration of a document, a sale deed, an encumbrance certificate or what the registration records show.',
    keywords: 'registration, registered document, sale deed, sub registrar, encumbrance certificate, document registration, deed, conveyance, gift deed, settlement deed, sold, sale',
    departments: ['CTR'],
    required_documents: 'Copy of the document relied upon, encumbrance certificate, patta, identity proof.' },

  { short_name: 'Transfer of Property Act, 1882',
    full_title: 'The Transfer of Property Act, 1882',
    act_type: A, year: 1882, jurisdiction: C,
    applies_when: 'A petition concerns transfer of immovable property by sale, gift, mortgage, lease or exchange.',
    keywords: 'transfer of property, sale, gift, mortgage, lease, immovable property, property transfer, title, conveyance, sold without consent',
    departments: ['CTR', 'REVENUE'] },

  { short_name: 'Indian Succession Act, 1925',
    full_title: 'The Indian Succession Act, 1925',
    act_type: A, year: 1925, jurisdiction: C,
    applies_when: 'A petition concerns succession, a will, probate or a legal heir certificate.',
    keywords: 'succession, will, probate, legal heir, inheritance, heirship certificate, deceased, death of owner',
    departments: ['REVENUE', 'LAW'],
    required_documents: 'Death certificate, relationship proof, will if any, property document.' },

  { short_name: 'Hindu Succession Act, 1956',
    full_title: 'The Hindu Succession Act, 1956',
    act_type: A, year: 1956, jurisdiction: C,
    applies_when: 'A petition concerns inheritance of property among Hindu heirs, including a daughter or widow claiming a share.',
    keywords: 'hindu succession, inheritance, coparcener, ancestral property, daughter share, widow share, family property, partition, legal heir',
    departments: ['REVENUE', 'LAW'] },

  { short_name: 'Hindu Marriage Act, 1955',
    full_title: 'The Hindu Marriage Act, 1955',
    act_type: A, year: 1955, jurisdiction: C,
    applies_when: 'A petition concerns marriage, divorce, judicial separation or restitution among Hindus.',
    keywords: 'marriage, divorce, husband, wife, judicial separation, marriage certificate, matrimonial',
    departments: ['LAW', 'SWWE'] },

  { short_name: 'Hindu Adoptions and Maintenance Act, 1956',
    full_title: 'The Hindu Adoptions and Maintenance Act, 1956',
    act_type: A, year: 1956, jurisdiction: C,
    applies_when: 'A petition concerns adoption, or maintenance claimed by a wife, child or aged parent under Hindu law.',
    keywords: 'adoption, maintenance, wife maintenance, aged parent, dependent, adopted child',
    departments: ['SWWE', 'LAW'] },

  { short_name: 'Special Marriage Act, 1954',
    full_title: 'The Special Marriage Act, 1954',
    act_type: A, year: 1954, jurisdiction: C,
    applies_when: 'A petition concerns a civil marriage or inter-faith marriage registration.',
    keywords: 'special marriage, civil marriage, inter caste marriage, inter faith, marriage registration',
    departments: ['CTR', 'LAW'] },

  { short_name: 'Indian Contract Act, 1872',
    full_title: 'The Indian Contract Act, 1872',
    act_type: A, year: 1872, jurisdiction: C,
    applies_when: 'A petition concerns an agreement, breach of contract or an unfulfilled promise between parties.',
    keywords: 'contract, agreement, breach, promise, advance amount, non performance, deal',
    departments: ['LAW'] },

  { short_name: 'Arbitration and Conciliation Act, 1996',
    full_title: 'The Arbitration and Conciliation Act, 1996',
    act_type: A, year: 1996, jurisdiction: C,
    applies_when: 'A petition concerns arbitration, conciliation or an arbitral award.',
    keywords: 'arbitration, conciliation, arbitral award, arbitrator, dispute resolution',
    departments: ['LAW'] },

  { short_name: 'Code of Civil Procedure, 1908',
    full_title: 'The Code of Civil Procedure, 1908',
    act_type: A, year: 1908, jurisdiction: C,
    applies_when: 'A petition concerns civil court procedure, execution of a decree or a civil suit.',
    keywords: 'civil suit, decree, execution, civil court, injunction, civil procedure, stay order',
    departments: ['LAW'] },

  { short_name: 'Bharatiya Nyaya Sanhita, 2023',
    full_title: 'The Bharatiya Nyaya Sanhita, 2023',
    act_type: A, year: 2023, jurisdiction: C,
    applies_when: 'A petition alleges conduct that may amount to a criminal offence.',
    keywords: 'criminal, offence, theft, cheating, fraud, assault, forgery, criminal complaint, crime, threat',
    departments: ['HOME'] },

  { short_name: 'Bharatiya Nagarik Suraksha Sanhita, 2023',
    full_title: 'The Bharatiya Nagarik Suraksha Sanhita, 2023',
    act_type: A, year: 2023, jurisdiction: C,
    applies_when: 'A petition concerns criminal procedure, registration of a complaint, investigation or bail.',
    keywords: 'fir, police complaint, investigation, criminal procedure, bail, summons, charge sheet, police not registering',
    departments: ['HOME'] },

  { short_name: 'Bharatiya Sakshya Adhiniyam, 2023',
    full_title: 'The Bharatiya Sakshya Adhiniyam, 2023',
    act_type: A, year: 2023, jurisdiction: C,
    applies_when: 'A matter concerns evidence and its admissibility.',
    keywords: 'evidence, witness, document evidence, proof, admissibility',
    departments: ['LAW', 'HOME'] },

  { short_name: 'Child and Adolescent Labour (Prohibition and Regulation) Act, 1986',
    full_title: 'The Child and Adolescent Labour (Prohibition and Regulation) Act, 1986',
    act_type: A, year: 1986, jurisdiction: C,
    applies_when: 'A petition concerns employment of a child or adolescent in work.',
    keywords: 'child labour, adolescent labour, child working, underage worker, child employment',
    departments: ['LABOUR', 'SOCDEF'],
    priority: 'URGENT' },

  { short_name: 'MGNREGA, 2005',
    full_title: 'The Mahatma Gandhi National Rural Employment Guarantee Act, 2005',
    act_type: A, year: 2005, jurisdiction: C,
    applies_when: 'A petition concerns rural employment guarantee work, job cards or non-payment of wages under the scheme.',
    keywords: 'mgnrega, nrega, job card, hundred days work, rural employment, employment guarantee, wage not paid, muster roll, work demand',
    departments: ['RDPR'],
    required_documents: 'Job card copy, work demand application, bank passbook.' },

  { short_name: 'National Food Security Act, 2013',
    full_title: 'The National Food Security Act, 2013',
    act_type: A, year: 2013, jurisdiction: C,
    applies_when: 'A petition concerns ration entitlement, ration card, or supply from a fair price shop.',
    keywords: 'ration card, ration, food security, fair price shop, pds, rice, provisions, smart card, ration not given',
    departments: ['COOP'],
    required_documents: 'Ration card copy, identity proof, address proof.' },

  { short_name: 'National Rural Livelihoods Mission framework',
    full_title: 'National Rural Livelihoods Mission - applicable framework',
    act_type: F, year: null, jurisdiction: C,
    applies_when: 'A petition concerns self help groups, rural livelihood support or micro credit under the mission.',
    keywords: 'self help group, shg, rural livelihood, micro credit, women group, livelihood mission, nrlm',
    departments: ['RDPR'] },

  { short_name: 'Employees Provident Funds and Miscellaneous Provisions Act, 1952',
    full_title: 'The Employees Provident Funds and Miscellaneous Provisions Act, 1952',
    act_type: A, year: 1952, jurisdiction: C,
    applies_when: 'A petition concerns provident fund contribution, withdrawal, transfer or pension under EPF.',
    keywords: 'provident fund, pf, epf, employer not remitting, pf withdrawal, uan, epf pension',
    departments: ['LABOUR'] },

  { short_name: 'Employees State Insurance Act, 1948',
    full_title: 'The Employees State Insurance Act, 1948',
    act_type: A, year: 1948, jurisdiction: C,
    applies_when: 'A petition concerns ESI benefits, medical treatment under ESI or employer contribution.',
    keywords: 'esi, employees state insurance, esi hospital, esi benefit, sickness benefit, esi contribution',
    departments: ['LABOUR'] },

  { short_name: 'Minimum wages framework',
    full_title: 'Minimum wages - applicable current framework',
    act_type: F, year: null, jurisdiction: C,
    applies_when: 'A petition concerns payment below the notified minimum wage.',
    keywords: 'minimum wage, wage rate, underpaid, low wage, notified wage',
    departments: ['LABOUR'] },

  { short_name: 'Payment of Wages framework',
    full_title: 'Payment of wages - applicable current framework',
    act_type: F, year: null, jurisdiction: C,
    applies_when: 'A petition concerns delay in payment of wages, unlawful deduction or non-payment.',
    keywords: 'wages not paid, salary delay, wage deduction, non payment, arrears of wages, pending salary',
    departments: ['LABOUR'] },

  { short_name: 'Occupational safety framework',
    full_title: 'Factories and occupational safety - applicable current framework',
    act_type: F, year: null, jurisdiction: C,
    applies_when: 'A petition concerns workplace safety, an industrial accident or unsafe working conditions.',
    keywords: 'factory safety, workplace accident, occupational safety, unsafe working, industrial accident, safety equipment',
    departments: ['LABOUR', 'IND'] },

  // ---------------- Tamil Nadu State Acts ----------------
  { short_name: 'Tamil Nadu Social Security Pension framework',
    full_title: 'Tamil Nadu social security pension schemes - applicable current framework',
    act_type: F, year: null, jurisdiction: S,
    applies_when:
      'A petition concerns old age pension, widow pension, destitute pension or another ' +
      'social security pension - its sanction, non-receipt, eligibility or discontinuation.',
    keywords:
      'old age pension, widow pension, destitute pension, social security pension, ' +
      'pension not received, pension application, pension sanction, monthly assistance, ' +
      'முதியோர் ஓய்வூதியம், விதவை ஓய்வூதியம், ஆதரவற்றோர் ஓய்வூதியம், ஓய்வூதியம் கிடைக்கவில்லை, ' +
      'மாத உதவி, ஓய்வூதிய விண்ணப்பம், ஓய்வூதியம் நிறுத்தப்பட்டது',
    departments: ['SWWE', 'REVENUE'],
    required_documents: 'Proof of age, income or destitution particulars, any earlier application and its acknowledgement, bank passbook.',
    recommended_action: 'Verify the eligibility particulars and the status of any pending application with the concerned office.',
    priority: 'HIGH' },

  { short_name: 'Tamil Nadu Land Encroachment Act, 1905',
    full_title: 'The Tamil Nadu Land Encroachment Act, 1905',
    act_type: A, year: 1905, jurisdiction: S,
    applies_when: 'A petition concerns encroachment on government land, poramboke land or unauthorised occupation.',
    keywords: 'encroachment, government land, poramboke, unauthorised occupation, land grab, occupied land, eviction',
    departments: ['REVENUE'],
    required_documents: 'Survey number particulars, patta, site sketch, any earlier complaint.' },

  { short_name: 'Tamil Nadu Patta Pass Book Act, 1983',
    full_title: 'The Tamil Nadu Patta Pass Book Act, 1983',
    act_type: A, year: 1983, jurisdiction: S,
    applies_when: 'A petition concerns patta, patta pass book, transfer of patta or a discrepancy in land records.',
    keywords: 'patta, patta pass book, chitta, land record, patta transfer, name change in patta, subdivision, adangal',
    departments: ['REVENUE'],
    required_documents: 'Existing patta copy, sale deed, chitta and adangal extract, identity proof.',
    priority: 'HIGH' },

  { short_name: 'Tamil Nadu Panchayats Act, 1994',
    full_title: 'The Tamil Nadu Panchayats Act, 1994',
    act_type: A, year: 1994, jurisdiction: S,
    applies_when: 'A petition concerns village panchayat administration, panchayat funds, gram sabha or a panchayat service.',
    keywords: 'panchayat, village panchayat, gram sabha, panchayat president, panchayat union, village administration, panchayat road, panchayat water',
    departments: ['RDPR'] },

  { short_name: 'Tamil Nadu Urban Local Bodies framework',
    full_title: 'Tamil Nadu urban local bodies - applicable current framework',
    act_type: F, year: null, jurisdiction: S,
    applies_when: 'A petition concerns a municipality or corporation service, urban civic amenity or local body administration.',
    keywords: 'municipality, corporation, urban local body, ward, councillor, civic amenity, ' +
      'municipal service, property tax, drinking water, water supply, no drinking water, ' +
      'street light, drainage, sewerage, garbage, sanitation, ' +
      'நகராட்சி, மாநகராட்சி, குடிநீர், தண்ணீர், குடிநீர் வரவில்லை, தெரு விளக்கு, சாக்கடை, குப்பை',
    departments: ['MAWS'] },

  { short_name: 'Tamil Nadu Town and Country Planning Act, 1971',
    full_title: 'The Tamil Nadu Town and Country Planning Act, 1971',
    act_type: A, year: 1971, jurisdiction: S,
    applies_when: 'A petition concerns planning permission, layout approval, land use or unauthorised construction.',
    keywords: 'planning permission, layout approval, land use, unauthorised construction, building plan, cmda, dtcp, deviation',
    departments: ['HOUSING'] },

  { short_name: 'Tamil Nadu Co-operative Societies Act, 1983',
    full_title: 'The Tamil Nadu Co-operative Societies Act, 1983',
    act_type: A, year: 1983, jurisdiction: S,
    applies_when: 'A petition concerns a co-operative society, co-operative bank loan, society election or society administration.',
    keywords: 'cooperative society, cooperative bank, society loan, society election, primary agricultural cooperative, member, society deposit',
    departments: ['COOP'] },

  { short_name: 'Tamil Nadu Agricultural Produce Marketing (Regulation) Act, 1987',
    full_title: 'The Tamil Nadu Agricultural Produce Marketing (Regulation) Act, 1987',
    act_type: A, year: 1987, jurisdiction: S,
    applies_when: 'A petition concerns a regulated market, agricultural produce sale or market committee.',
    keywords: 'agricultural market, regulated market, market committee, produce sale, procurement, uzhavar sandhai, mandi',
    departments: ['AGRI'] },

  { short_name: 'Tamil Nadu Forest Act, 1882',
    full_title: 'The Tamil Nadu Forest Act, 1882',
    act_type: A, year: 1882, jurisdiction: S,
    applies_when: 'A petition concerns reserve forest, forest produce or forest administration in the State.',
    keywords: 'forest, reserve forest, forest produce, tree cutting, forest department, forest offence',
    departments: ['ENV'] },

  { short_name: 'Tamil Nadu Prevention of Begging Act, 1945',
    full_title: 'The Tamil Nadu Prevention of Begging Act, 1945',
    act_type: A, year: 1945, jurisdiction: S,
    applies_when: 'A petition concerns destitute persons found begging or rehabilitation of such persons.',
    keywords: 'begging, destitute, beggar home, rehabilitation, homeless',
    departments: ['SOCDEF'] },

  { short_name: 'Tamil Nadu Prohibition of Charging Exorbitant Interest Act, 2003',
    full_title: 'The Tamil Nadu Prohibition of Charging Exorbitant Interest Act, 2003',
    act_type: A, year: 2003, jurisdiction: S,
    applies_when: 'A petition alleges money lending at exorbitant interest, harassment by a moneylender or usurious lending.',
    keywords: 'exorbitant interest, moneylender, private loan, usury, interest harassment, meter interest, loan harassment, blank cheque',
    departments: ['HOME'],
    priority: 'HIGH' },

  { short_name: 'Tamil Nadu Protection of Interests of Depositors Act, 1997',
    full_title: 'The Tamil Nadu Protection of Interests of Depositors (in Financial Establishments) Act, 1997',
    act_type: A, year: 1997, jurisdiction: S,
    applies_when: 'A petition concerns a financial establishment failing to repay deposits, or a deposit fraud.',
    keywords: 'deposit, financial establishment, chit fund, deposit not returned, investment fraud, depositor, finance company',
    departments: ['HOME', 'FIN'],
    priority: 'HIGH' },

  { short_name: 'Tamil Nadu Shops and Establishments framework',
    full_title: 'Tamil Nadu shops and establishments - applicable current framework',
    act_type: F, year: null, jurisdiction: S,
    applies_when: 'A petition concerns working conditions, hours or employment in a shop or commercial establishment.',
    keywords: 'shop, establishment, working hours, shop employee, commercial establishment, weekly holiday',
    departments: ['LABOUR'] },

  { short_name: 'Tamil Nadu Labour Welfare Fund Act, 1972',
    full_title: 'The Tamil Nadu Labour Welfare Fund Act, 1972',
    act_type: A, year: 1972, jurisdiction: S,
    applies_when: 'A petition concerns labour welfare fund benefits or contributions.',
    keywords: 'labour welfare fund, welfare board, worker welfare, welfare benefit, unorganised worker',
    departments: ['LABOUR'] },

  { short_name: 'Tamil Nadu Industrial Establishments (National and Festival Holidays) Act, 1958',
    full_title: 'The Tamil Nadu Industrial Establishments (National and Festival Holidays) Act, 1958',
    act_type: A, year: 1958, jurisdiction: S,
    applies_when: 'A petition concerns denial of national or festival holidays to workers.',
    keywords: 'festival holiday, national holiday, holiday denied, worker holiday',
    departments: ['LABOUR'] },

  { short_name: 'Tamil Nadu Private Colleges (Regulation) Act, 1976',
    full_title: 'The Tamil Nadu Private Colleges (Regulation) Act, 1976',
    act_type: A, year: 1976, jurisdiction: S,
    applies_when: 'A petition concerns a private college, its administration, staff or student matters.',
    keywords: 'private college, college management, college staff, college admission, college fee',
    departments: ['HIGHEDU'] },

  { short_name: 'Tamil Nadu Schools (Regulation of Collection of Fee) Act, 2009',
    full_title: 'The Tamil Nadu Schools (Regulation of Collection of Fee) Act, 2009',
    act_type: A, year: 2009, jurisdiction: S,
    applies_when: 'A petition concerns excess school fee collection or unauthorised fees by a private school.',
    keywords: 'school fee, excess fee, fee collection, private school fee, fee committee, donation demanded',
    departments: ['SCHEDU'],
    required_documents: 'Fee receipt, school circular, admission record.' },

  { short_name: 'Tamil Nadu Recognised Private Schools (Regulation) Act, 1973',
    full_title: 'The Tamil Nadu Recognised Private Schools (Regulation) Act, 1973',
    act_type: A, year: 1973, jurisdiction: S,
    applies_when: 'A petition concerns a recognised private school, its recognition, staff or administration.',
    keywords: 'private school, school recognition, school management, school teacher, school administration',
    departments: ['SCHEDU'] },

  { short_name: 'Tamil Nadu Fire and Rescue Services Act, 2025',
    full_title: 'The Tamil Nadu Fire and Rescue Services Act, 2025',
    act_type: A, year: 2025, jurisdiction: S,
    applies_when: 'A petition concerns fire safety, fire service response or a fire no-objection certificate.',
    keywords: 'fire safety, fire service, fire noc, fire accident, rescue, fire station',
    departments: ['HOME'] },

  { short_name: 'Tamil Nadu Highways Act, 2001',
    full_title: 'The Tamil Nadu Highways Act, 2001',
    act_type: A, year: 2001, jurisdiction: S,
    applies_when: 'A petition concerns a state highway, road widening, highway land or road maintenance.',
    keywords: 'highway, road widening, highway land, road maintenance, bypass, road damage, service road',
    departments: ['HIGHWAYS'] },

  { short_name: 'Tamil Nadu Maritime Board Act, 1995',
    full_title: 'The Tamil Nadu Maritime Board Act, 1995',
    act_type: A, year: 1995, jurisdiction: S,
    applies_when: 'A petition concerns minor ports or maritime administration.',
    keywords: 'port, maritime, harbour, minor port, jetty, shipping',
    departments: ['HIGHWAYS'] },

  { short_name: 'Tamil Nadu Tax on Consumption or Sale of Electricity Act, 2003',
    full_title: 'The Tamil Nadu Tax on Consumption or Sale of Electricity Act, 2003',
    act_type: A, year: 2003, jurisdiction: S,
    applies_when: 'A petition concerns electricity tax on consumption or sale.',
    keywords: 'electricity tax, electricity duty, power tax, consumption tax',
    departments: ['ENERGY'] },

  { short_name: 'Tamil Nadu Goods and Services Tax Act, 2017',
    full_title: 'The Tamil Nadu Goods and Services Tax Act, 2017',
    act_type: A, year: 2017, jurisdiction: S,
    applies_when: 'A petition concerns GST registration, returns, refund or assessment.',
    keywords: 'gst, goods and services tax, gst registration, gst refund, tax assessment, input credit, gstin',
    departments: ['CTR'] },

  { short_name: 'Tamil Nadu Fiscal Responsibility Act, 2003',
    full_title: 'The Tamil Nadu Fiscal Responsibility Act, 2003',
    act_type: A, year: 2003, jurisdiction: S,
    applies_when: 'A matter concerns state fiscal management and responsibility.',
    keywords: 'fiscal responsibility, state finance, fiscal deficit, budget management',
    departments: ['FIN'] },

  { short_name: 'Tamil Nadu Acquisition of Lands for Industrial Purposes Act, 1997',
    full_title: 'The Tamil Nadu Acquisition of Lands for Industrial Purposes Act, 1997',
    act_type: A, year: 1997, jurisdiction: S,
    applies_when: 'A petition concerns acquisition of land for an industrial purpose and compensation for it.',
    keywords: 'industrial land acquisition, sipcot land, industrial purpose, acquisition compensation, industrial estate land',
    departments: ['IND', 'REVENUE'] },

  { short_name: 'Tamil Nadu Land Reforms (Fixation of Ceiling on Land) Act, 1961',
    full_title: 'The Tamil Nadu Land Reforms (Fixation of Ceiling on Land) Act, 1961',
    act_type: A, year: 1961, jurisdiction: S,
    applies_when: 'A petition concerns land ceiling, surplus land or land reform proceedings.',
    keywords: 'land ceiling, surplus land, land reform, ceiling limit, excess land, assignment',
    departments: ['REVENUE'] },

  { short_name: 'Tamil Nadu Cultivating Tenants Protection Act, 1955',
    full_title: 'The Tamil Nadu Cultivating Tenants Protection Act, 1955',
    act_type: A, year: 1955, jurisdiction: S,
    applies_when: 'A petition concerns a cultivating tenant, eviction from agricultural land or tenancy rights.',
    keywords: 'cultivating tenant, tenant farmer, eviction, tenancy, agricultural tenant, lease land, kuthagai',
    departments: ['REVENUE', 'AGRI'] },

  { short_name: 'Tamil Nadu Agricultural Lands Record of Tenancy Rights Act, 1969',
    full_title: 'The Tamil Nadu Agricultural Lands Record of Tenancy Rights Act, 1969',
    act_type: A, year: 1969, jurisdiction: S,
    applies_when: 'A petition concerns recording of tenancy rights in agricultural land.',
    keywords: 'tenancy right, record of tenancy, agricultural tenancy, tenant record',
    departments: ['REVENUE'] },

  { short_name: 'Tamil Nadu Slum Areas (Improvement and Clearance) Act, 1971',
    full_title: 'The Tamil Nadu Slum Areas (Improvement and Clearance) Act, 1971',
    act_type: A, year: 1971, jurisdiction: S,
    applies_when: 'A petition concerns a slum area, slum clearance, resettlement or tenement allotment.',
    keywords: 'slum, slum clearance, tenement, resettlement, slum board, hut, relocation',
    departments: ['HOUSING'] },

  { short_name: 'Tamil Nadu District Municipalities Act, 1920',
    full_title: 'The Tamil Nadu District Municipalities Act, 1920',
    act_type: A, year: 1920, jurisdiction: S,
    applies_when: 'A petition concerns municipal administration, municipal tax or a municipal service.',
    keywords: 'municipality, municipal tax, property tax, municipal service, town panchayat, municipal licence, trade licence',
    departments: ['MAWS'] },

  { short_name: 'Tamil Nadu Hindu Religious and Charitable Endowments Act, 1959',
    full_title: 'The Tamil Nadu Hindu Religious and Charitable Endowments Act, 1959',
    act_type: A, year: 1959, jurisdiction: S,
    applies_when: 'A petition concerns a temple, temple land, temple administration or a charitable endowment.',
    keywords: 'temple, hr ce, temple land, endowment, trustee, temple administration, religious institution, temple property, archaka',
    departments: ['HRCE', 'TOURISM'] },

  { short_name: 'Tamil Nadu Protection of Tanks and Eviction of Encroachment Act, 2007',
    full_title: 'The Tamil Nadu Protection of Tanks and Eviction of Encroachment Act, 2007',
    act_type: A, year: 2007, jurisdiction: S,
    applies_when: 'A petition concerns encroachment of a tank, waterbody or its channel.',
    keywords: 'tank encroachment, waterbody, eri, kulam, lake encroachment, channel, water body encroachment, canal encroachment',
    departments: ['WATERRES', 'REVENUE'] },

  { short_name: 'Tamil Nadu Private Schools Fee Regulation framework',
    full_title: 'Tamil Nadu private schools fee regulation - applicable current framework',
    act_type: F, year: null, jurisdiction: S,
    applies_when: 'A petition concerns regulation of fees charged by private schools.',
    keywords: 'school fee regulation, fee fixation, private school fee, fee committee',
    departments: ['SCHEDU'] },

  { short_name: 'Tamil Nadu Prevention of Dangerous Activities Act, 1982',
    full_title: 'The Tamil Nadu Prevention of Dangerous Activities of Bootleggers, Drug Offenders, Goondas and other offenders Act, 1982',
    act_type: A, year: 1982, jurisdiction: S,
    applies_when: 'A petition concerns habitual offenders, goondas or preventive detention.',
    keywords: 'goonda, rowdy, preventive detention, habitual offender, bootlegger, drug offender, land grabber',
    departments: ['HOME'] },

  { short_name: 'Tamil Nadu Prohibition Act, 1937',
    full_title: 'The Tamil Nadu Prohibition Act, 1937',
    act_type: A, year: 1937, jurisdiction: S,
    applies_when: 'A petition concerns illicit liquor, prohibition offences or a liquor outlet.',
    keywords: 'liquor, illicit liquor, tasmac, prohibition, arrack, alcohol, liquor shop, sarakku',
    departments: ['HOME'] },

  { short_name: 'Tamil Nadu Gaming Act, 1930',
    full_title: 'The Tamil Nadu Gaming Act, 1930',
    act_type: A, year: 1930, jurisdiction: S,
    applies_when: 'A petition concerns gambling or a gaming house.',
    keywords: 'gambling, gaming, betting, card game, online gambling, satta',
    departments: ['HOME'] },

  { short_name: 'Tamil Nadu Regulation of Rights and Responsibilities of Landlords and Tenants Act, 2017',
    full_title: 'The Tamil Nadu Regulation of Rights and Responsibilities of Landlords and Tenants Act, 2017',
    act_type: A, year: 2017, jurisdiction: S,
    applies_when: 'A petition concerns a rented premises, landlord-tenant dispute, rent or eviction from a tenancy.',
    keywords: 'rent, landlord, tenant, eviction, rental agreement, advance amount, rent control, house rent, vacate',
    departments: ['HOUSING'] },

  { short_name: 'Tamil Nadu Apartment Ownership Act, 2022',
    full_title: 'The Tamil Nadu Apartment Ownership Act, 2022',
    act_type: A, year: 2022, jurisdiction: S,
    applies_when: 'A petition concerns apartment ownership, common areas or an apartment owners association.',
    keywords: 'apartment, flat owner, association, common area, maintenance charge, apartment association, builder handover',
    departments: ['HOUSING'] },

  { short_name: 'Tamil Nadu Combined Development and Building Rules, 2019',
    full_title: 'The Tamil Nadu Combined Development and Building Rules, 2019',
    act_type: 'RULE', year: 2019, jurisdiction: S,
    applies_when: 'A petition concerns building rules, setback, floor area or building regulation compliance.',
    keywords: 'building rule, setback, floor area, building regulation, construction deviation, building violation, fsi',
    departments: ['HOUSING'] },

  { short_name: 'Tamil Nadu Transparency in Tenders Act, 1998',
    full_title: 'The Tamil Nadu Transparency in Tenders Act, 1998',
    act_type: A, year: 1998, jurisdiction: S,
    applies_when: 'A petition concerns a government tender process or tender irregularity.',
    keywords: 'tender, tender process, contract award, bidding, tender irregularity, government contract',
    departments: ['FIN', 'PWD'] },

  { short_name: 'Tamil Nadu Protection of Traditional Rights of Fishing Community Act, 2020',
    full_title: 'The Tamil Nadu Protection of Interests and Traditional Rights of the Fishing Community Act, 2020',
    act_type: A, year: 2020, jurisdiction: S,
    applies_when: 'A petition concerns fishermen rights, fishing access or coastal livelihood.',
    keywords: 'fishermen, fishing, fisherman rights, coastal, boat, sea, fishing ground, kuppam',
    departments: ['AHDF'] },

  { short_name: 'Tamil Nadu Agricultural University Act',
    full_title: 'Tamil Nadu Agricultural University Act and amendments',
    act_type: A, year: null, jurisdiction: S,
    applies_when: 'A petition concerns the Agricultural University, its administration, staff or students.',
    keywords: 'agricultural university, tnau, agriculture college, agri student',
    departments: ['HIGHEDU', 'AGRI'] },

  { short_name: 'Tamil Nadu Veterinary and Animal Sciences University Act',
    full_title: 'Tamil Nadu Veterinary and Animal Sciences University Act and amendments',
    act_type: A, year: null, jurisdiction: S,
    applies_when: 'A petition concerns the Veterinary University, its administration, staff or students.',
    keywords: 'veterinary university, tanuvas, veterinary college, animal science',
    departments: ['HIGHEDU', 'AHDF'] },

  { short_name: 'Tamil Nadu Dr. M.G.R. Medical University Act',
    full_title: 'Tamil Nadu Dr. M.G.R. Medical University Act and amendments',
    act_type: A, year: null, jurisdiction: S,
    applies_when: 'A petition concerns the Medical University, medical college affiliation, staff or students.',
    keywords: 'medical university, mgr medical university, medical college, mbbs, medical student, affiliation',
    departments: ['HIGHEDU', 'HEALTH'] },

  { short_name: 'Tamil Nadu Dr. Ambedkar Law University Act',
    full_title: 'Tamil Nadu Dr. Ambedkar Law University Act and amendments',
    act_type: A, year: null, jurisdiction: S,
    applies_when: 'A petition concerns the Law University, law college, staff or students.',
    keywords: 'law university, ambedkar law university, law college, law student',
    departments: ['HIGHEDU', 'LAW'] },

  { short_name: 'Tamil Nadu Universities Laws',
    full_title: 'Tamil Nadu Universities Laws and amendments',
    act_type: A, year: null, jurisdiction: S,
    applies_when: 'A petition concerns a state university, its administration, appointments or student matters.',
    keywords: 'university, vice chancellor, university administration, syndicate, university appointment, convocation, degree certificate',
    departments: ['HIGHEDU'] },

  { short_name: 'Tamil Nadu Prohibition of Ragging Act, 1997',
    full_title: 'The Tamil Nadu Prohibition of Ragging Act, 1997',
    act_type: A, year: 1997, jurisdiction: S,
    applies_when: 'A petition alleges ragging in an educational institution.',
    keywords: 'ragging, senior student, hostel harassment, college harassment, ragging complaint',
    departments: ['HIGHEDU', 'HOME'],
    priority: 'URGENT' },

  { short_name: 'Tamil Nadu private tuition centres framework',
    full_title: 'Tamil Nadu private tuition centres - applicable current regulatory framework',
    act_type: F, year: null, jurisdiction: S,
    applies_when: 'A petition concerns a private tuition centre or coaching institution.',
    keywords: 'tuition centre, coaching centre, private tuition, coaching institute',
    departments: ['SCHEDU'] },

  { short_name: 'Tamil Nadu SC/ST welfare rules and schemes',
    full_title: 'Tamil Nadu Scheduled Caste and Scheduled Tribe welfare rules and schemes',
    act_type: F, year: null, jurisdiction: S,
    applies_when: 'A petition concerns SC/ST welfare schemes, scholarships, hostels or benefits in the State.',
    keywords: 'sc st welfare, scholarship, adi dravidar hostel, welfare scheme, community benefit, free education',
    departments: ['ADW'] },

  { short_name: 'Tamil Nadu State Commission for Women framework',
    full_title: 'Tamil Nadu State Commission for Women - applicable framework',
    act_type: F, year: null, jurisdiction: S,
    applies_when: 'A petition concerns a complaint by or on behalf of a woman suitable for the State Commission for Women.',
    keywords: 'women commission, women complaint, woman harassment, women rights, state commission for women',
    departments: ['SWWE'] },

  { short_name: 'Tamil Nadu State Commission for Protection of Child Rights framework',
    full_title: 'Tamil Nadu State Commission for Protection of Child Rights - applicable framework',
    act_type: F, year: null, jurisdiction: S,
    applies_when: 'A petition concerns violation of child rights.',
    keywords: 'child rights, child commission, child protection, child welfare committee, child complaint',
    departments: ['SOCDEF', 'SWWE'] },

  { short_name: 'Tamil Nadu State Human Rights Commission framework',
    full_title: 'Tamil Nadu State Human Rights Commission - applicable framework',
    act_type: F, year: null, jurisdiction: S,
    applies_when: 'A petition alleges violation of human rights by a public servant or authority.',
    keywords: 'human rights, human rights commission, custodial, police excess, rights violation, shrc',
    departments: ['HOME', 'PUBLIC'] },

  { short_name: 'Tamil Nadu State Legal Services Authority framework',
    full_title: 'Tamil Nadu State Legal Services Authority - applicable framework',
    act_type: F, year: null, jurisdiction: S,
    applies_when: 'A petitioner may need free legal aid or lok adalat assistance in the State.',
    keywords: 'legal services authority, legal aid, lok adalat, free advocate, legal assistance, tnslsa',
    departments: ['LAW'] },

  { short_name: 'Tamil Nadu Electricity Regulatory Commission framework',
    full_title: 'Tamil Nadu Electricity Regulatory Commission - applicable framework',
    act_type: F, year: null, jurisdiction: S,
    applies_when: 'A petition concerns electricity tariff, supply, a new connection, billing or a power failure.',
    keywords: 'electricity, eb, power, tangedco, meter, electricity bill, power cut, new connection, transformer, tariff, current',
    departments: ['ENERGY'] },

  { short_name: 'Tamil Nadu Pollution Control Board framework',
    full_title: 'Tamil Nadu Pollution Control Board - applicable regulatory framework',
    act_type: F, year: null, jurisdiction: S,
    applies_when: 'A petition concerns pollution by an industry or establishment, consent to operate, or environmental nuisance.',
    keywords: 'pollution control board, tnpcb, consent to operate, industrial pollution, effluent, noise pollution, smell, factory pollution',
    departments: ['ENV'] },

  { short_name: 'Tamil Nadu RERA framework',
    full_title: 'Tamil Nadu Real Estate Regulatory Authority - applicable framework',
    act_type: F, year: null, jurisdiction: S,
    applies_when: 'A petition concerns a registered real estate project, promoter obligation or possession delay in the State.',
    keywords: 'tnrera, rera, promoter, builder, project registration, possession, real estate complaint',
    departments: ['HOUSING'] },

  { short_name: 'Tamil Nadu clinical establishments framework',
    full_title: 'Tamil Nadu clinical establishments - applicable health regulatory framework',
    act_type: F, year: null, jurisdiction: S,
    applies_when: 'A petition concerns a hospital, clinic or nursing home, its registration, charges or standard of care.',
    keywords: 'hospital, clinic, nursing home, private hospital, medical negligence, hospital charges, treatment denied, clinical establishment',
    departments: ['HEALTH'] },

  { short_name: 'Tamil Nadu labour compliance framework',
    full_title: 'Tamil Nadu shops and establishments - current labour compliance framework',
    act_type: F, year: null, jurisdiction: S,
    applies_when: 'A petition concerns labour compliance, registration or inspection of an establishment.',
    keywords: 'labour compliance, labour inspection, establishment registration, labour licence, compliance',
    departments: ['LABOUR'] },
];

// ========================================================== AUTHORITIES
export const TN_AUTHORITIES: {
  designation: string; department: string; office_name: string;
  level: 'STATE' | 'DISTRICT' | 'TALUK' | 'VILLAGE'; area: string;
  responsibilities: string; keywords: string;
}[] = [
  { designation: 'District Collector', department: 'REVENUE', office_name: 'District Collectorate',
    level: 'DISTRICT', area: 'District',
    responsibilities: 'District administration, public grievance redressal, land administration and coordination between departments.',
    keywords: 'collector, district, grievance, petition, land, coordination' },
  { designation: 'Revenue Divisional Officer', department: 'REVENUE', office_name: 'Revenue Divisional Office',
    level: 'DISTRICT', area: 'Revenue division',
    responsibilities: 'Revenue appeals, land matters at divisional level and enquiries referred by the Collector.',
    keywords: 'rdo, revenue divisional officer, appeal, enquiry, sub collector, land matter' },
  { designation: 'Tahsildar', department: 'REVENUE', office_name: 'Taluk Office',
    level: 'TALUK', area: 'Taluk',
    responsibilities: 'Land records, patta transfer, mutation, revenue certificates and taluk revenue administration.',
    keywords: 'tahsildar, patta, land record, mutation, certificate, taluk office, chitta' },
  { designation: 'Village Administrative Officer', department: 'REVENUE', office_name: 'Village Office',
    level: 'VILLAGE', area: 'Village',
    responsibilities: 'Village land records, field verification and reporting to the Tahsildar.',
    keywords: 'vao, village administrative officer, village office, field verification, village record' },
  { designation: 'Sub Registrar', department: 'CTR', office_name: 'Sub Registrar Office',
    level: 'TALUK', area: 'Registration sub district',
    responsibilities: 'Registration of documents, encumbrance certificates and registration records.',
    keywords: 'sub registrar, registration, sale deed, encumbrance certificate, document' },
  { designation: 'District Registrar', department: 'CTR', office_name: 'District Registrar Office',
    level: 'DISTRICT', area: 'Registration district',
    responsibilities: 'Supervision of sub registrar offices and registration appeals.',
    keywords: 'district registrar, registration appeal, registration supervision' },
  { designation: 'District Social Welfare Officer', department: 'SWWE', office_name: 'District Social Welfare Office',
    level: 'DISTRICT', area: 'District',
    responsibilities: 'Pension schemes, women and child welfare, senior citizen welfare and social security schemes.',
    keywords: 'social welfare officer, pension, welfare, women, senior citizen, elderly, scheme' },
  { designation: 'Maintenance Tribunal (Revenue Divisional Officer)', department: 'SWWE',
    office_name: 'Maintenance Tribunal', level: 'DISTRICT', area: 'Revenue division',
    responsibilities: 'Applications for maintenance by parents and senior citizens.',
    keywords: 'maintenance tribunal, senior citizen maintenance, parent maintenance, tribunal' },
  { designation: 'District Supply Officer', department: 'COOP', office_name: 'District Supply Office',
    level: 'DISTRICT', area: 'District',
    responsibilities: 'Ration cards, public distribution system and fair price shop administration.',
    keywords: 'supply officer, ration card, fair price shop, pds, food supply, provisions' },
  { designation: 'Superintendent of Police', department: 'HOME', office_name: 'District Police Office',
    level: 'DISTRICT', area: 'District',
    responsibilities: 'District police administration, law and order and police complaints.',
    keywords: 'police, sp, superintendent of police, law and order, complaint, fir' },
  { designation: 'Station House Officer', department: 'HOME', office_name: 'Police Station',
    level: 'TALUK', area: 'Police station limit',
    responsibilities: 'Registration of complaints, investigation and local law and order.',
    keywords: 'police station, sho, inspector, fir, complaint, investigation' },
  { designation: 'Joint Director of Health Services', department: 'HEALTH', office_name: 'District Health Office',
    level: 'DISTRICT', area: 'District',
    responsibilities: 'District health administration, government hospitals and primary health centres.',
    keywords: 'health officer, hospital, phc, medical, health services, deputy director health' },
  { designation: 'Chief Educational Officer', department: 'SCHEDU', office_name: 'District Education Office',
    level: 'DISTRICT', area: 'District',
    responsibilities: 'School administration, admissions, teachers and school fee matters in the district.',
    keywords: 'ceo education, chief educational officer, school, admission, teacher, school fee' },
  { designation: 'District Educational Officer', department: 'SCHEDU', office_name: 'District Educational Office',
    level: 'DISTRICT', area: 'Educational district',
    responsibilities: 'Supervision of schools and school level grievances.',
    keywords: 'deo, district educational officer, school supervision, school complaint' },
  { designation: 'Block Development Officer', department: 'RDPR', office_name: 'Block Development Office',
    level: 'TALUK', area: 'Panchayat union block',
    responsibilities: 'Panchayat administration, rural schemes, MGNREGA and rural development works.',
    keywords: 'bdo, block development officer, panchayat, rural, mgnrega, village work' },
  { designation: 'District Collector (Disaster Management)', department: 'REVENUE',
    office_name: 'District Disaster Management Authority', level: 'DISTRICT', area: 'District',
    responsibilities: 'Disaster relief, flood and drought relief and calamity assistance.',
    keywords: 'disaster, flood, relief, calamity, drought, cyclone, damage' },
  { designation: 'Commissioner, Municipal Corporation', department: 'MAWS', office_name: 'Municipal Corporation',
    level: 'DISTRICT', area: 'Corporation limit',
    responsibilities: 'Corporation administration, civic services, water supply and sanitation.',
    keywords: 'corporation commissioner, municipal, civic, water supply, garbage, street light, road' },
  { designation: 'Municipal Commissioner', department: 'MAWS', office_name: 'Municipality',
    level: 'TALUK', area: 'Municipal limit',
    responsibilities: 'Municipal administration, civic amenities and municipal taxes.',
    keywords: 'municipal commissioner, municipality, civic amenity, property tax, town' },
  { designation: 'Executive Engineer, TANGEDCO', department: 'ENERGY', office_name: 'Electricity Board Office',
    level: 'DISTRICT', area: 'Electricity distribution circle',
    responsibilities: 'Electricity supply, new connections, billing and fault rectification.',
    keywords: 'electricity, eb, tangedco, power, meter, connection, transformer, bill, power cut' },
  { designation: 'Regional Transport Officer', department: 'TRANSPORT', office_name: 'Regional Transport Office',
    level: 'DISTRICT', area: 'Transport district',
    responsibilities: 'Driving licences, vehicle registration, permits and fitness certificates.',
    keywords: 'rto, driving licence, vehicle registration, permit, fitness, transport office' },
  { designation: 'Deputy Commissioner of Labour', department: 'LABOUR', office_name: 'Labour Office',
    level: 'DISTRICT', area: 'District',
    responsibilities: 'Labour disputes, wages, working conditions and labour welfare.',
    keywords: 'labour officer, wages, worker, labour dispute, labour welfare, salary complaint' },
  { designation: 'District Environmental Engineer, TNPCB', department: 'ENV',
    office_name: 'Tamil Nadu Pollution Control Board District Office', level: 'DISTRICT', area: 'District',
    responsibilities: 'Pollution complaints, consent to operate and environmental compliance.',
    keywords: 'pollution, tnpcb, environmental engineer, effluent, air pollution, noise, industry pollution' },
  { designation: 'District Forest Officer', department: 'ENV', office_name: 'District Forest Office',
    level: 'DISTRICT', area: 'Forest division',
    responsibilities: 'Forest administration, wildlife matters and forest offences.',
    keywords: 'forest officer, dfo, forest, wildlife, tree, elephant, forest land' },
  { designation: 'Joint Director of Agriculture', department: 'AGRI', office_name: 'District Agriculture Office',
    level: 'DISTRICT', area: 'District',
    responsibilities: 'Agricultural schemes, crop support, seeds, fertiliser and farmer welfare.',
    keywords: 'agriculture officer, farmer, crop, seed, fertiliser, agricultural scheme, subsidy' },
  { designation: 'District Adi Dravidar Welfare Officer', department: 'ADW',
    office_name: 'District Adi Dravidar Welfare Office', level: 'DISTRICT', area: 'District',
    responsibilities: 'SC/ST welfare schemes, hostels, scholarships and community certificates.',
    keywords: 'adi dravidar welfare, sc st welfare, scholarship, hostel, community certificate' },
  { designation: 'District Backward Classes Welfare Officer', department: 'BCMBC',
    office_name: 'District Backward Classes Welfare Office', level: 'DISTRICT', area: 'District',
    responsibilities: 'Backward class and minority welfare schemes and scholarships.',
    keywords: 'backward class welfare, bc mbc, minority welfare, scholarship' },
  { designation: 'District Differently Abled Welfare Officer', department: 'WDAP',
    office_name: 'District Differently Abled Welfare Office', level: 'DISTRICT', area: 'District',
    responsibilities: 'Disability certificates, assistive devices, disability pension and welfare schemes.',
    keywords: 'differently abled, disability, disability certificate, disability pension, assistive device' },
  { designation: 'Secretary, District Legal Services Authority', department: 'LAW',
    office_name: 'District Legal Services Authority', level: 'DISTRICT', area: 'District',
    responsibilities: 'Free legal aid, legal counselling and lok adalat.',
    keywords: 'legal services authority, legal aid, lok adalat, free legal, dlsa' },
  { designation: 'Executive Engineer, Public Works Department', department: 'PWD', office_name: 'PWD Division Office',
    level: 'DISTRICT', area: 'PWD division',
    responsibilities: 'Government buildings, irrigation works, tanks and canals.',
    keywords: 'pwd, public works, irrigation, tank, canal, building, dam' },
  { designation: 'Divisional Engineer, Highways', department: 'HIGHWAYS', office_name: 'Highways Division Office',
    level: 'DISTRICT', area: 'Highways division',
    responsibilities: 'State highways, road construction and road maintenance.',
    keywords: 'highways, road, road repair, pothole, road widening, bridge' },
  { designation: 'Executive Officer, Temple (HR&CE)', department: 'HRCE', office_name: 'Temple Administration Office',
    level: 'DISTRICT', area: 'Temple jurisdiction',
    responsibilities: 'Temple administration, temple lands and endowment matters.',
    keywords: 'temple, hr ce, executive officer, temple land, endowment, trustee' },
  { designation: 'Assistant Director, Town and Country Planning', department: 'HOUSING',
    office_name: 'Town and Country Planning Office', level: 'DISTRICT', area: 'Planning district',
    responsibilities: 'Planning permission, layout approval and land use regulation.',
    keywords: 'dtcp, town planning, layout approval, planning permission, land use, building plan' },
  { designation: 'Deputy Registrar of Co-operative Societies', department: 'COOP',
    office_name: 'Co-operative Societies Office', level: 'DISTRICT', area: 'District',
    responsibilities: 'Co-operative societies, society elections, audits and member grievances.',
    keywords: 'cooperative society, registrar of societies, society election, society loan, cooperative bank' },
  { designation: 'Assistant Commissioner (Commercial Taxes)', department: 'CTR',
    office_name: 'Commercial Taxes Office', level: 'DISTRICT', area: 'Assessment circle',
    responsibilities: 'GST assessment, registration and commercial tax matters.',
    keywords: 'commercial tax, gst, assessment, tax officer, gst registration' },
  { designation: 'District Child Protection Officer', department: 'SOCDEF',
    office_name: 'District Child Protection Unit', level: 'DISTRICT', area: 'District',
    responsibilities: 'Child protection, children in need of care and child welfare committee support.',
    keywords: 'child protection, child welfare, juvenile, children home, child officer' },
  { designation: 'Assistant Director, Fisheries', department: 'AHDF', office_name: 'District Fisheries Office',
    level: 'DISTRICT', area: 'District',
    responsibilities: 'Fishermen welfare, fishing regulation and fisheries schemes.',
    keywords: 'fisheries, fishermen, boat, fishing, marine, fisheries officer' },
  { designation: 'Regional Joint Director, Animal Husbandry', department: 'AHDF',
    office_name: 'Animal Husbandry Office', level: 'DISTRICT', area: 'District',
    responsibilities: 'Veterinary services, livestock and dairy development.',
    keywords: 'veterinary, animal husbandry, cattle, livestock, dairy, milk' },
  { designation: 'General Manager, District Industries Centre', department: 'MSME',
    office_name: 'District Industries Centre', level: 'DISTRICT', area: 'District',
    responsibilities: 'MSME registration, subsidies and entrepreneurship support.',
    keywords: 'dic, district industries centre, msme, subsidy, entrepreneur, small industry' },
  { designation: 'Public Information Officer', department: 'PAR', office_name: 'Concerned public authority',
    level: 'DISTRICT', area: 'Public authority',
    responsibilities: 'Providing information under the Right to Information Act.',
    keywords: 'public information officer, pio, rti, information, appellate authority' },
  { designation: 'Electoral Registration Officer', department: 'ELECTION', office_name: 'Electoral Office',
    level: 'TALUK', area: 'Assembly constituency',
    responsibilities: 'Electoral roll, voter registration and voter identity matters.',
    keywords: 'voter, electoral roll, voter id, epic, election, ero' },
  { designation: 'Executive Engineer, Water Resources Department', department: 'WATERRES',
    office_name: 'Water Resources Division Office', level: 'DISTRICT', area: 'Irrigation division',
    responsibilities: 'Irrigation channels, tanks, canals, waterbodies and water resource works.',
    keywords: 'water resources, tank, canal, irrigation, waterbody, eri, kulam, channel, encroachment of tank' },
  { designation: 'Assistant Director, Town Panchayat', department: 'MAWS', office_name: 'Town Panchayat Office',
    level: 'TALUK', area: 'Town panchayat',
    responsibilities: 'Town panchayat administration, civic amenities and local services.',
    keywords: 'town panchayat, civic, local body, street light, water supply' },
  { designation: 'District Employment Officer', department: 'LABOUR', office_name: 'District Employment Exchange',
    level: 'DISTRICT', area: 'District',
    responsibilities: 'Employment registration, job seeker support and employment exchange services.',
    keywords: 'employment exchange, job seeker, employment registration, unemployment' },
  { designation: 'Assistant Engineer, Highways', department: 'HIGHWAYS', office_name: 'Highways Section Office',
    level: 'TALUK', area: 'Highways section',
    responsibilities: 'Local road maintenance and highway section works.',
    keywords: 'road repair, pothole, road maintenance, highway section' },
  { designation: 'Treasury Officer', department: 'TREASURY', office_name: 'District Treasury',
    level: 'DISTRICT', area: 'District',
    responsibilities: 'Treasury payments, pension disbursement and government accounts.',
    keywords: 'treasury, pension payment, government account, bill payment, pensioner' },
];

// =============================================================== SUBJECTS
export const TN_SUBJECTS: {
  code: string; name: string; description: string; keywords: string;
  department: string; priority: string;
}[] = [
  { code: 'LAND_RECORDS', name: 'Land Records / Patta',
    description: 'Patta, chitta, survey, mutation and land record matters.',
    keywords: 'patta, chitta, survey number, mutation, land record, subdivision, adangal, name change',
    department: 'REVENUE', priority: 'NORMAL' },
  { code: 'LAND_ENCROACHMENT', name: 'Land Encroachment',
    description: 'Encroachment on government land, waterbody or private property.',
    keywords: 'encroachment, government land, poramboke, land grab, occupied, unauthorised occupation',
    department: 'REVENUE', priority: 'HIGH' },
  { code: 'PROPERTY_TRANSFER', name: 'Property Sale / Transfer',
    description: 'Sale, gift or transfer of property and registration matters.',
    keywords: 'sale deed, sold, property sold, registration, transfer, gift deed, without consent, without knowledge',
    department: 'CTR', priority: 'HIGH' },
  { code: 'SENIOR_CITIZEN', name: 'Senior Citizen Welfare',
    description: 'Elderly persons, maintenance, livelihood difficulty and senior citizen welfare.',
    keywords: 'senior citizen, elderly, aged, old age, maintenance, livelihood, destitute, grandmother, unable to maintain, abandoned',
    department: 'SWWE', priority: 'HIGH' },
  { code: 'PENSION_SCHEME', name: 'Pension / Social Security',
    description: 'Old age, widow and disability pension and other social security schemes.',
    keywords: 'pension, old age pension, widow pension, disability pension, not received, sanction, scheme, monthly assistance',
    department: 'SWWE', priority: 'HIGH' },
  { code: 'WOMEN_SAFETY', name: 'Women Safety and Welfare',
    description: 'Violence, harassment or welfare matters concerning women.',
    keywords: 'woman, domestic violence, harassment, dowry, wife, women safety, eve teasing, abuse',
    department: 'SWWE', priority: 'URGENT' },
  { code: 'CHILD_WELFARE', name: 'Child Welfare and Protection',
    description: 'Children in need of care, child labour and child rights.',
    keywords: 'child, minor, child labour, child protection, orphan, school child, juvenile',
    department: 'SOCDEF', priority: 'URGENT' },
  { code: 'DISABILITY', name: 'Disability Welfare',
    description: 'Disability certification, benefits and accessibility.',
    keywords: 'disability, differently abled, disabled, handicapped, disability certificate, wheelchair, blind, deaf',
    department: 'WDAP', priority: 'HIGH' },
  { code: 'RATION_PDS', name: 'Ration and Food Supply',
    description: 'Ration card, fair price shop and food supply matters.',
    keywords: 'ration card, ration, fair price shop, pds, rice, provisions, smart card',
    department: 'COOP', priority: 'HIGH' },
  { code: 'HEALTH_SERVICE', name: 'Health and Medical',
    description: 'Hospitals, medical treatment and health services.',
    keywords: 'hospital, medical, doctor, treatment, phc, medicine, ambulance, patient, health',
    department: 'HEALTH', priority: 'HIGH' },
  { code: 'EDUCATION', name: 'Education',
    description: 'School and college admission, fees and education matters.',
    keywords: 'school, college, admission, student, teacher, school fee, education, ragging',
    department: 'SCHEDU', priority: 'NORMAL' },
  { code: 'CIVIC_WATER', name: 'Water Supply and Sanitation',
    description: 'Drinking water, drainage, sewerage and sanitation.',
    keywords: 'drinking water, water supply, tap, drainage, sewerage, garbage, sanitation, underground drainage',
    department: 'MAWS', priority: 'HIGH' },
  { code: 'CIVIC_ROAD', name: 'Roads and Infrastructure',
    description: 'Road condition, street lights and public infrastructure.',
    keywords: 'road, pothole, street light, bridge, road repair, highway, footpath',
    department: 'HIGHWAYS', priority: 'NORMAL' },
  { code: 'ELECTRICITY', name: 'Electricity Supply',
    description: 'Power connection, billing, transformers and power failure.',
    keywords: 'electricity, eb, power, current, meter, transformer, power cut, bill, connection',
    department: 'ENERGY', priority: 'HIGH' },
  { code: 'EMPLOYMENT_WAGES', name: 'Employment and Wages',
    description: 'Wages, employment, labour disputes and worker welfare.',
    keywords: 'wages, salary, worker, labour, employment, job, esi, provident fund, unemployment, bonded labour',
    department: 'LABOUR', priority: 'HIGH' },
  { code: 'AGRICULTURE', name: 'Agriculture and Farmer Welfare',
    description: 'Crop, irrigation, farmer schemes and agricultural support.',
    keywords: 'farmer, crop, agriculture, seed, fertiliser, irrigation, cultivation, crop loss, crop insurance',
    department: 'AGRI', priority: 'HIGH' },
  { code: 'POLICE_MATTER', name: 'Police and Law Order',
    description: 'Police complaints, law and order and public safety.',
    keywords: 'police, fir, complaint, threat, assault, theft, law and order, station, crime',
    department: 'HOME', priority: 'URGENT' },
  { code: 'POLLUTION', name: 'Pollution and Environment',
    description: 'Air, water and noise pollution and environmental damage.',
    keywords: 'pollution, effluent, smoke, noise, environment, waste, contamination, industry pollution',
    department: 'ENV', priority: 'HIGH' },
  { code: 'HOUSING_MATTER', name: 'Housing and Building',
    description: 'Housing schemes, building approval, rent and apartment matters.',
    keywords: 'house, housing, building approval, rent, landlord, tenant, apartment, slum, tenement, construction',
    department: 'HOUSING', priority: 'NORMAL' },
  { code: 'TRANSPORT_MATTER', name: 'Transport and Vehicles',
    description: 'Driving licence, vehicle registration, permits and bus services.',
    keywords: 'bus, vehicle, driving licence, rto, permit, transport, accident, registration certificate',
    department: 'TRANSPORT', priority: 'NORMAL' },
  { code: 'RTI_MATTER', name: 'Right to Information',
    description: 'Information requests and RTI appeals.',
    keywords: 'rti, right to information, information request, pio, information denied, appeal',
    department: 'PAR', priority: 'NORMAL' },
  { code: 'GENERAL', name: 'General Grievance',
    description: 'Matters not falling within a specific configured subject.',
    keywords: 'grievance, complaint, request, general, petition, help',
    department: 'PUBLIC', priority: 'NORMAL' },
];
